GOPATH_PREFIX=github.com
PROJECT_NAME=bccp-server
MYSQL_PKG=${GOPATH_PREFIX}/${PROJECT_NAME}/mysql
RUNNERS_PKG=${GOPATH_PREFIX}/${PROJECT_NAME}/runners
API_PKG=${GOPATH_PREFIX}/${PROJECT_NAME}/api
MAIN_PKG=${GOPATH_PREFIX}/${PROJECT_NAME}/bccp

CONFIG_DIR=/etc/bccp
DEFAULT_CONFIG_FILE=bccp.conf

GO=go
GO_FLAGS=install

all: ${MYSQL_PKG} ${RUNNERS_PKG} ${API_PKG} ${MAIN_PKG}

install: config
config: ${CONFIG_DIR}
	cp ${DEFAULT_CONFIG_FILE} ${CONFIG_DIR}

${CONFIG_DIR}:
	mkdir -p ${CONFIG_DIR}


Makefile: ;
.DEFAULT:
	${GO} ${GO_FLAGS} $@
